#!/usr/bin/env bash
# Bash script that displays Best School 10 times, 
# but for the 9th iteration, 
# displays Best School and then Hi on a new line

counter=1

while [ $counter -lt 10 ]
do
    if [ $counter == 9 ]
then
    echo -e "Best School\nHi"
fi
    echo "Best School"
    counter=$((counter+1))
done
